theme: jekyll-theme-minimal
title: Ellie's Portfolio
description: Welcome to my website!
logo: <img src="https://user-images.githubusercontent.com/51255260/210165542-b9f4cb71-cbf9-4809-af7f-cc94dcf7b736.png">

